# Fly.io configuration for Protectogram v3.1 (Staging)
app = "protectogram-staging"
primary_region = "cdg"  # Paris

[build]

[env]
  ENVIRONMENT = "staging"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false  # Keep running for webhook reliability
  auto_start_machines = true   # For scaling additional machines
  min_machines_running = 1     # Always have 1 machine for webhooks
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

[[http_service.checks]]
  grace_period = "10s"
  interval = "60s"
  method = "GET"
  timeout = "10s"
  path = "/health"

# Smaller VMs for staging
[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

# Process definitions (combined for cost efficiency)
[processes]
  app = "python -m uvicorn app.factory:create_staging_app --factory --host 0.0.0.0 --port 8000"

# Staging secrets (set with: flyctl secrets set -a protectogram-staging KEY=VALUE)
# Required secrets:
# - DATABASE_URL (Supabase staging)
# - REDIS_URL (Upstash staging)
# - TELEGRAM_BOT_TOKEN (@ProtectogramTestBot)
# - TWILIO_ACCOUNT_SID (test account)
# - TWILIO_AUTH_TOKEN (test account)
# - TWILIO_FROM_NUMBER
# - SECRET_KEY
# - SENTRY_DSN (optional)
