# Fly.io configuration for Protectogram v3.1 (Production)
app = "protectogram"
primary_region = "cdg"  # Paris - optimal for Spain/Russia latency

[build]

[env]
  ENVIRONMENT = "production"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

# Web application process
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Celery worker process  
[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ["worker"]

# Celery beat process
[[vm]]
  memory = '256mb'  
  cpu_kind = 'shared'
  cpus = 1
  processes = ["beat"]

# Process definitions
[processes]
  app = "python -m uvicorn app.factory:create_production_app --factory --host 0.0.0.0 --port 8000"
  worker = "celery -A app.celery_app worker --loglevel=info --queues=panic_alerts,trip_reminders,notifications,default --concurrency=2"
  beat = "celery -A app.celery_app beat --loglevel=info"

# Secrets (set with: flyctl secrets set KEY=VALUE)
# Required secrets:
# - DATABASE_URL (Supabase PostgreSQL)
# - REDIS_URL (Upstash Redis)
# - TELEGRAM_BOT_TOKEN
# - TWILIO_ACCOUNT_SID
# - TWILIO_AUTH_TOKEN  
# - TWILIO_FROM_NUMBER
# - SECRET_KEY
# - WEBHOOK_SECRET
# - SENTRY_DSN (optional)