# Fly.io configuration for Protectogram
app = "protectogram-staging"
primary_region = "cdg"

[env]
APP_ENV = "staging"

# HTTP service for web process
[[services]]
protocol = "http"
internal_port = 8000
processes = ["web"]

# Port configuration for web service
[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

# Health checks for web service
[[services.http_checks]]
interval = "30s"
timeout = "10s"
grace_period = "5s"
method = "GET"
path = "/health/live"
protocol = "http"

[[services.http_checks]]
interval = "60s"
timeout = "10s"
grace_period = "5s"
method = "GET"
path = "/health/ready"
protocol = "http"

# Metrics endpoint check
[[services.http_checks]]
interval = "120s"
timeout = "10s"
grace_period = "5s"
method = "GET"
path = "/metrics"
protocol = "http"

# Process groups
[processes]
web = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
scheduler = "python -m app.scheduler.setup"

# Web process VM - increased memory for FastAPI + DB connections + metrics
[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
processes = ["web"]

# Scheduler process VM - increased memory for APScheduler + job persistence
[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
processes = ["scheduler"]
