# Fly.io configuration for Protectogram v3.1 (Production)
app = "protectogram"
primary_region = "cdg"  # Paris - optimal for Spain/Russia latency

[build]
  [build.args]
    ENV = "prod"

[env]
  ENVIRONMENT = "production"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false  # Never suspend - safety-critical app
  auto_start_machines = true   # For scaling additional machines
  min_machines_running = 1     # Always available for emergencies
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

# Production VMs - more powerful than staging
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2

# Process definitions
[processes]
  app = "python -m uvicorn app.factory:create_production_app --factory --host 0.0.0.0 --port 8000"

# Secrets (set with: flyctl secrets set KEY=VALUE)
# Required secrets:
# - DATABASE_URL (Supabase PostgreSQL)
# - REDIS_URL (Upstash Redis)
# - TELEGRAM_BOT_TOKEN
# - TWILIO_ACCOUNT_SID
# - TWILIO_AUTH_TOKEN
# - TWILIO_FROM_NUMBER
# - SECRET_KEY
# - WEBHOOK_SECRET
# - SENTRY_DSN (optional)
