# Fly.io configuration for Protectogram
app = "protectogram-staging"
primary_region = "iad"

[env]
APP_ENV = "staging"

# HTTP service for web process
[[services]]
protocol = "http"
internal_port = 8000
processes = ["web"]

# Health checks for web service
[[services.http_checks]]
interval = "30s"
timeout = "10s"
grace_period = "5s"
method = "GET"
path = "/health/live"
protocol = "http"

[[services.http_checks]]
interval = "60s"
timeout = "10s"
grace_period = "5s"
method = "GET"
path = "/health/ready"
protocol = "http"

# Process groups
[processes]
web = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
scheduler = "python -m app.scheduler.setup"

# Web process VM
[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
processes = ["web"]

# Scheduler process VM
[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
processes = ["scheduler"]

# Metrics endpoint
[[services]]
protocol = "http"
internal_port = 8000
processes = ["web"]

[[services.http_checks]]
interval = "120s"
timeout = "10s"
grace_period = "5s"
method = "GET"
path = "/metrics"
protocol = "http"
