# Fly.io configuration for Protectogram
app = "protectogram-staging"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  APP_ENV = "staging"
  SCHEDULER_ENABLED = "true"

# HTTP service for web process only
[[services]]
protocol = "tcp"
internal_port = 8080
processes = ["web"]

# Port configuration for web service
[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]

# Health checks for web service
[[services.http_checks]]
interval = "10s"
timeout = "2s"
method = "GET"
path = "/health/live"
protocol = "http"
tls_skip_verify = false
restart_limit = 0

# Process groups
[processes]
web = "uvicorn app.main:app --host 0.0.0.0 --port 8080"
scheduler = "python -m app.scheduler.run"

# Web process VM - increased memory for FastAPI + DB connections + metrics
[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
processes = ["web"]

# Scheduler process VM - increased memory for APScheduler + job persistence
[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
processes = ["scheduler"]

[deploy]
  # Run migrations once per deploy in an ephemeral VM
  release_command = "cd /app && alembic upgrade head"
