app = "protectogram-staging"

[build]

[env]
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health/live"

[[processes]]
  name = "web"
  cmd = "uvicorn app.main:app --host 0.0.0.0 --port 8080"

[[processes]]
  name = "scheduler"
  cmd = "python -m app.scheduler"
  processes = ["scheduler"]
