"""Remove timezone and is_active columns from users table

Revision ID: f55a995e0b02
Revises: 75c66b2a8600
Create Date: 2025-09-01 22:26:29.034503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f55a995e0b02"
down_revision: Union[str, None] = "75c66b2a8600"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "timezone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "timezone",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
            comment="User timezone (tz database name)",
        ),
    )
    # ### end Alembic commands ###
