"""Remove email field from users table

Revision ID: 50f9239565ef
Revises: f55a995e0b02
Create Date: 2025-09-02 00:04:32.187068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50f9239565ef"
down_revision: Union[str, None] = "f55a995e0b02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="User's email address",
        ),
    )
    # ### end Alembic commands ###
