"""Add missing user fields (telegram_username, first_name, last_name, email)

Revision ID: 75c66b2a8600
Revises: ae42b859e4e0
Create Date: 2025-09-01 21:54:34.928893

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75c66b2a8600"
down_revision: Union[str, None] = "ae42b859e4e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add nullable columns first
    op.add_column(
        "users",
        sa.Column(
            "telegram_username",
            sa.String(length=100),
            nullable=True,
            comment="Telegram username (without @)",
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "first_name",
            sa.String(length=100),
            nullable=True,  # Temporarily nullable
            comment="User's first name",
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "last_name",
            sa.String(length=100),
            nullable=True,
            comment="User's last name",
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=True,
            comment="User's email address",
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "preferred_language",
            sa.String(length=5),
            nullable=True,  # Temporarily nullable
            comment="User preferred language (ISO 639-1)",
        ),
    )

    # Step 2: Update existing users with default values
    # Copy language to preferred_language and set defaults
    op.execute(
        "UPDATE users SET preferred_language = COALESCE(language, 'en') WHERE preferred_language IS NULL"
    )
    op.execute("UPDATE users SET first_name = 'User' WHERE first_name IS NULL")

    # Step 3: Make required columns non-nullable
    op.alter_column("users", "first_name", nullable=False)
    op.alter_column("users", "preferred_language", nullable=False)

    # Step 4: Drop old language column
    op.drop_column("users", "language")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "language",
            sa.VARCHAR(length=5),
            autoincrement=False,
            nullable=False,
            comment="User preferred language (ISO 639-1)",
        ),
    )
    op.drop_column("users", "preferred_language")
    op.drop_column("users", "email")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "telegram_username")
    # ### end Alembic commands ###
