"""Increase status column length for notification attempts

Revision ID: d7c995e2a3b4
Revises: 998f6f94f69f
Create Date: 2025-09-03 22:35:02.865980

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7c995e2a3b4"  # pragma: allowlist secret
down_revision: Union[str, None] = "998f6f94f69f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "panic_notification_attempts",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=30),
        existing_comment="Attempt status: sent, delivered, failed, acknowledged_positive, acknowledged_negative",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "panic_notification_attempts",
        "status",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=20),
        existing_comment="Attempt status: sent, delivered, failed, acknowledged_positive, acknowledged_negative",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
