"""Add guardian registration and consent fields

Revision ID: 1b4eeae8dbae
Revises: d7c995e2a3b4
Create Date: 2025-09-04 18:37:43.252597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b4eeae8dbae"
down_revision: Union[str, None] = "d7c995e2a3b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guardians",
        sa.Column(
            "telegram_chat_id",
            sa.BigInteger(),
            nullable=True,
            comment="Telegram chat ID for sending messages to guardian",
        ),
    )
    op.add_column(
        "guardians",
        sa.Column(
            "telegram_username",
            sa.String(length=100),
            nullable=True,
            comment="Telegram username if available",
        ),
    )
    op.add_column(
        "guardians",
        sa.Column(
            "invitation_token",
            sa.String(length=64),
            nullable=True,
            comment="Unique invitation token for registration",
        ),
    )
    op.add_column(
        "guardians",
        sa.Column(
            "invited_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When invitation was sent",
        ),
    )
    op.add_column(
        "guardians",
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When guardian completed registration",
        ),
    )
    # Add columns with defaults for existing data
    op.add_column(
        "guardians",
        sa.Column(
            "consent_given",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
            comment="Whether guardian has given explicit consent",
        ),
    )
    op.add_column(
        "guardians",
        sa.Column(
            "verification_status",
            sa.String(length=30),
            nullable=False,
            server_default=sa.text("'pending'"),
            comment="Verification status: pending, telegram_verified, phone_verified, fully_verified, declined",
        ),
    )
    op.add_column(
        "guardians",
        sa.Column(
            "preferred_contact_method",
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'both'"),
            comment="Preferred contact method: phone, telegram, both",
        ),
    )
    op.add_column(
        "guardians",
        sa.Column(
            "invitation_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When invitation token expires (7 days from creation)",
        ),
    )
    op.create_index(
        op.f("ix_guardians_invitation_token"),
        "guardians",
        ["invitation_token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_guardians_telegram_chat_id"),
        "guardians",
        ["telegram_chat_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_guardians_telegram_chat_id"), table_name="guardians")
    op.drop_index(op.f("ix_guardians_invitation_token"), table_name="guardians")
    op.drop_column("guardians", "preferred_contact_method")
    op.drop_column("guardians", "invitation_expires_at")
    op.drop_column("guardians", "verification_status")
    op.drop_column("guardians", "consent_given")
    op.drop_column("guardians", "registered_at")
    op.drop_column("guardians", "invited_at")
    op.drop_column("guardians", "invitation_token")
    op.drop_column("guardians", "telegram_username")
    op.drop_column("guardians", "telegram_chat_id")
    # ### end Alembic commands ###
